name: Merge Master
on: 
  push:
    branches:
      - master
jobs:
  testin-master:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: install
        run: npm install
      
      - name: testing
        run: npm run test
